[tool.black]
line-length = 100
preview = true
include = '(ai_diffusion|scripts|tests)/.*\.pyi?$'
extend-exclude = 'websockets|krita\.pyi$'

[tool.pyright]
include = ["ai_diffusion", "scripts/*.py", "tests"]
exclude = [
    "**/__pycache__",
    "**/.pytest_cache",
    "**/.server",
    "tests/server",
    "ai_diffusion/websockets",
    "test_pod.py",
]
ignore = ["ai_diffusion/websockets", "krita.pyi"]
extraPaths = ["scripts/typeshed"]
reportMissingModuleSource = false
